require 'rspec/core/rake_task'
require 'rake/testtask'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = '-r ./spec/spec_helper.rb --format Fuubar --color'
  t.verbose = false
end

desc 'Run all specs'
task test: [:spec]

task default: [:test]
